const colors = {
  light: {
    text: "#1C1C1E",
    tint: "#C8102E",
    background: "#FAFAF8",
    foreground: "#1C1C1E",
    card: "#FFFFFF",
    cardForeground: "#1C1C1E",
    primary: "#C8102E",
    primaryForeground: "#FFFFFF",
    secondary: "#F4F4F4",
    secondaryForeground: "#1C1C1E",
    muted: "#F4F4F4",
    mutedForeground: "#8A8A8E",
    accent: "#FFF0F0",
    accentForeground: "#C8102E",
    destructive: "#FF3B30",
    destructiveForeground: "#FFFFFF",
    border: "#E5E5EA",
    input: "#E5E5EA",
    success: "#34C759",
    successForeground: "#FFFFFF",
    warning: "#FF9500",
    warningForeground: "#FFFFFF",
  },
  dark: {
    text: "#F2F2F7",
    tint: "#FF453A",
    background: "#1C1C1E",
    foreground: "#F2F2F7",
    card: "#2C2C2E",
    cardForeground: "#F2F2F7",
    primary: "#FF453A",
    primaryForeground: "#FFFFFF",
    secondary: "#3A3A3C",
    secondaryForeground: "#F2F2F7",
    muted: "#2C2C2E",
    mutedForeground: "#8D8D93",
    accent: "#3D1515",
    accentForeground: "#FF6B6B",
    destructive: "#FF453A",
    destructiveForeground: "#FFFFFF",
    border: "#3A3A3C",
    input: "#3A3A3C",
    success: "#30D158",
    successForeground: "#FFFFFF",
    warning: "#FF9F0A",
    warningForeground: "#FFFFFF",
  },
  radius: 12,
};

export default colors;
